<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_LOGOUT</name>
   <tag></tag>
   <elementGuidId>27183ef6-eea1-48a2-aeba-ccf08b1834b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/a[5]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;LOGOUT&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6aadc260-8a0f-4918-9e82-8f4a83bf4f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-16 border-4 border-gray-500 font-bold text-slate-950 hover:bg-gray-100 hover:text-gray-700 opacity-100 square3 </value>
      <webElementGuid>8157c89e-1505-4fbb-893a-573e5839f194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGOUT</value>
      <webElementGuid>9232176d-542a-477f-93a5-dc458ac9e5b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;big-container grid min-h-screen max-h-screen&quot;]/div[@class=&quot;p-4 grid gap-4 lg:grid-cols-3&quot;]/div[@class=&quot;grid place-items-center col-start-2&quot;]/div[@class=&quot;grid gap-4&quot;]/a[5]/button[@class=&quot;h-16 border-4 border-gray-500 font-bold text-slate-950 hover:bg-gray-100 hover:text-gray-700 opacity-100 square3&quot;]</value>
      <webElementGuid>20b36834-b38b-4562-b058-0b162c90f3da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/a[5]/button</value>
      <webElementGuid>09ae4fc9-0b14-488c-9fda-9aa5fe5a9116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROFILE'])[1]/following::button[1]</value>
      <webElementGuid>d1f4e167-289a-4f0f-8f7f-6c9ba997518d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANALYSIS'])[1]/following::button[2]</value>
      <webElementGuid>8d945674-33e7-4fb4-9582-8092f54d5f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LOGOUT']/parent::*</value>
      <webElementGuid>9d27c085-9c0a-4170-be24-c45bd75bd752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]/button</value>
      <webElementGuid>3ec0f5d0-ee09-4e4a-8fa8-5ce173e8fd0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'LOGOUT' or . = 'LOGOUT')]</value>
      <webElementGuid>b1031c1e-cae0-44af-92d0-36f5fa295a6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
