<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_View Routine_grid place-content-center _849044</name>
   <tag></tag>
   <elementGuidId>647b7ff9-415b-4c9a-8b45-a4dbc4ab50ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.grid.place-content-center.add-routine.bg-slate-100.bg-opacity-30.border-dashed.border-4.cursor-pointer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3c3df063-1001-43fb-92aa-d7853d175b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grid place-content-center add-routine bg-slate-100 bg-opacity-30 border-dashed border-4 cursor-pointer</value>
      <webElementGuid>fc2b94d8-e7ba-4b25-a23a-2ee52c556d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;yoga-container grid grid-cols-2 p-4 gap-2&quot;]/div[@class=&quot;flex flex-wrap col-span-1 justify-center&quot;]/div[@class=&quot;flex-1&quot;]/div[@class=&quot;grid place-content-center add-routine bg-slate-100 bg-opacity-30 border-dashed border-4 cursor-pointer&quot;]</value>
      <webElementGuid>93ec554a-3b24-4c25-bbc0-9f442a3d7258</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]</value>
      <webElementGuid>88ad4c2a-9014-4305-9b40-5dd77c6a29bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Routine'])[2]/following::div[1]</value>
      <webElementGuid>db9eef00-f4d3-44a7-9158-fdf8419564a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='routine 1'])[1]/following::div[1]</value>
      <webElementGuid>ab3b0924-fed6-485c-95d8-7ae0d6895098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instructions'])[1]/preceding::div[1]</value>
      <webElementGuid>e9199e63-bf52-4c52-8aed-2d6600d6d06b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return'])[1]/preceding::div[8]</value>
      <webElementGuid>c49499f0-cf9c-43c8-8bf8-943945b7ff44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]</value>
      <webElementGuid>16ec9a8e-9502-41c6-b9c3-e90f3b72d185</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
