<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email address_floatingPassword (2)</name>
   <tag></tag>
   <elementGuidId>51df0c16-0ed4-49b9-9d6d-0cbf1597cca3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#floatingPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='floatingPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba866686-e78b-4adb-83a9-5c6a2365a97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>23d7dfc2-2cad-44ba-ac3e-6fa39f5d20a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control rounded-3</value>
      <webElementGuid>af6924ab-58a3-4a84-b3a2-282d0fad441b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>floatingPassword</value>
      <webElementGuid>5062f109-ea1d-4143-94c1-52dd82b9d4f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>5bd46dc6-855d-4e84-85b7-1d9bc5fecfe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c18eddb5-1da4-44d4-812c-1cadc594bd51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;floatingPassword&quot;)</value>
      <webElementGuid>389cf4b3-a1dd-41b6-b38b-1032d92af215</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='floatingPassword']</value>
      <webElementGuid>ecf03ad1-82b9-4559-ab1c-9016a5c8e88e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-:r1:']/div/div[2]/form/div[2]/input</value>
      <webElementGuid>78976b18-edd7-47d6-8761-08175f5bf31b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>5cc3e019-aa8c-418d-8f0f-dbede003d3fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'floatingPassword' and @placeholder = 'Password']</value>
      <webElementGuid>f33a7586-d8de-47d3-a88e-ad9f4d50fb5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
