<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Routine Name_RoutineName (2)</name>
   <tag></tag>
   <elementGuidId>2f46c1e0-d4d8-43c2-9769-c2a8e45bd2ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RoutineName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RoutineName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>784cd776-0e01-4cd2-b570-783164f66d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1e94789c-3be2-4a43-b416-f1b3dd7c0b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8908d29b-daab-4857-9b7f-bc6e44157bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RoutineName</value>
      <webElementGuid>2be65831-2b33-462b-85a1-8a2d614b8f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>routine name</value>
      <webElementGuid>a26c767f-d37b-4c36-91fb-7df5a3776186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RoutineName&quot;)</value>
      <webElementGuid>b252d785-aebe-40a2-8fd0-3dc5332d5f3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RoutineName']</value>
      <webElementGuid>de8750f8-d885-4b9e-b22c-555bed69fcef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-:r4:']/div/div[2]/form/div/input</value>
      <webElementGuid>532d7ae2-55dc-440d-95fe-e1a957d8bdfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8c599205-14ba-48d6-80ec-8ad4ad41ead6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'RoutineName' and @placeholder = 'routine name']</value>
      <webElementGuid>e433fc8f-4f73-482b-ab96-cf6e131a5bb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
