<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Routine Name_RoutineName</name>
   <tag></tag>
   <elementGuidId>aef78a69-6ece-48b3-92bd-e9a3caeaae66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RoutineName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RoutineName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1721a72e-9a23-4b72-b49b-e7c2e3a9f245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9fe953be-5c23-4438-806e-0ebf1e978d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ec3c46de-1041-48ce-b7fe-d29d5a19a511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RoutineName</value>
      <webElementGuid>cc5eb333-2251-408f-a522-0837e3e0823b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>routine name</value>
      <webElementGuid>05112af6-1808-449c-bbdf-8d1231fd86bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RoutineName&quot;)</value>
      <webElementGuid>31907089-fb21-4652-8bbb-feb11cb03af5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RoutineName']</value>
      <webElementGuid>bd3ffbdf-889d-49cf-b11b-65360ab89b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-:r4:']/div/div[2]/form/div/input</value>
      <webElementGuid>4d705127-338d-4f0a-8e00-cab50dd908cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>945787a6-42b0-4ec7-b5e3-3e529bbd51e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'RoutineName' and @placeholder = 'routine name']</value>
      <webElementGuid>35f30aae-a324-4988-959d-0e47e3956f27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
