<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Routine Name_RoutineName (1)</name>
   <tag></tag>
   <elementGuidId>cf1811b8-7c59-4cd4-9b9c-b32be7f2e21b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RoutineName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RoutineName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>208e94d6-4b9e-4888-95d5-52c86841fc46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8898062-583b-43ab-9d95-86aa5a98d533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e290f4bd-dd07-44a1-be6a-537b9aa9e45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RoutineName</value>
      <webElementGuid>6b2d02f6-919b-4562-a0f8-f70e7e758524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>routine name</value>
      <webElementGuid>5c6d78c7-d5f6-4ccf-9f77-51806871658b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RoutineName&quot;)</value>
      <webElementGuid>64eb16f6-4b52-4cc2-85c7-4c59125799fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RoutineName']</value>
      <webElementGuid>60ad88ed-4ef8-4eb4-a9f9-172a8ff3c120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-:r4:']/div/div[2]/form/div/input</value>
      <webElementGuid>f4a48804-d108-417d-9a42-d4876a09c507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>001749a2-c5d1-4fab-ae7e-92c9f6943d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'RoutineName' and @placeholder = 'routine name']</value>
      <webElementGuid>00ce7d25-7080-4c2d-8fbb-10ac87a8567d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
