<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_View Routine_h-8 w-8 text-white</name>
   <tag></tag>
   <elementGuidId>74e1ee7c-a127-43a8-8d5c-d8b637ea01f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.h-8.w-8.text-white</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='View Routine'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>f22e2ae9-8ce9-49f3-b33f-9c3f7221b1dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>7dd8008c-d7f6-4c98-b551-1b8c3fa9649c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>89f06b9c-4136-40a8-9b75-68f8a05392cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>de5a4ac5-8516-4599-8c8d-ecc116adf679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>1.5</value>
      <webElementGuid>4d95a247-a1d3-4904-8d82-55feb23b2446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>339d78fc-7147-4313-b88a-b0ebb3340088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>80faa576-2a3d-4f78-b4e6-59feddfa8bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-8 w-8 text-white </value>
      <webElementGuid>07a8ed3b-2ba6-4b46-bbbc-f33c0e25636f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;yoga-container grid grid-cols-2 p-4 gap-2&quot;]/div[@class=&quot;flex flex-wrap col-span-1 justify-center&quot;]/div[@class=&quot;flex-1&quot;]/div[@class=&quot;grid place-content-center add-routine bg-slate-100 bg-opacity-30 border-dashed border-4 cursor-pointer&quot;]/svg[@class=&quot;h-8 w-8 text-white&quot;]</value>
      <webElementGuid>85b66dae-6e24-4e9d-b2f2-4c6ac1dade98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Routine'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>f4a6831a-df8a-4763-bf77-23d236b0bda9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='routine 1'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>34d00d34-f264-40de-8837-084a3506a6f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instructions'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>b336ffcd-802b-4cd8-b117-26efb7ea27b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>347777fb-51db-4a20-a30e-e0eb831c64f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
