<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Register</name>
   <tag></tag>
   <elementGuidId>87262fe2-769d-4790-a35c-d86756eb2eb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/nav/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mr-4.btn.btn-outline-light.border-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>21cca8d8-76e8-4f55-9de6-989fd7059e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> mr-4  btn btn-outline-light border-2 </value>
      <webElementGuid>3b07ad75-8cb6-4e70-8854-a9208b431c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>cec7615d-064a-4b65-be2e-0800e05ed8e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;big-container grid&quot;]/div[@class=&quot;gap-4 grid lg:grid-cols-2&quot;]/div[@class=&quot;right-side&quot;]/nav[@class=&quot;h-14  flex justify-end&quot;]/div[@class=&quot;m-3 pr-3&quot;]/button[@class=&quot;mr-4  btn btn-outline-light border-2&quot;]</value>
      <webElementGuid>2054dfa2-e66f-4de0-a20b-91088e5cf9f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/nav/div/button</value>
      <webElementGuid>9c61b7c7-0fa0-46c1-8f03-5d8b37208491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tester'])[1]/following::button[1]</value>
      <webElementGuid>54b1aff6-c384-45da-8cec-bfd70ddcb0c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/preceding::button[1]</value>
      <webElementGuid>2910600b-2eb6-42fa-b5c7-ee256b627802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Register']/parent::*</value>
      <webElementGuid>3a4f3a30-de6b-4111-be6e-9a08cc5250ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>d0f11db6-81e0-4d13-beb5-5d61e98ce27d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Register' or . = 'Register')]</value>
      <webElementGuid>303c0008-7ff0-4460-8288-07f9f781abcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
