<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email address  (e.g.,nameexample.com)_525eaa</name>
   <tag></tag>
   <elementGuidId>5c3c42f4-f167-40c7-8a86-cfcd0ebc3883</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registerPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#registerPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f562752-3463-4cb3-a63d-4cd7bb1a4b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e8322889-f169-441d-9b11-e11dceecb7a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control rounded-3</value>
      <webElementGuid>f7b03204-5947-4f6a-87b1-0f7d0ff24248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerPassword</value>
      <webElementGuid>3d3006ab-bff3-4c0c-931e-982de598e56e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>2b2a71d5-5a38-431d-9641-e8eb4bca15be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerPassword&quot;)</value>
      <webElementGuid>a7a1be86-7ddb-4bc3-8578-fc907e09f98b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registerPassword']</value>
      <webElementGuid>94672eef-9853-4343-812b-afdae4d1b901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-panel-:r1:']/div/div[2]/form/div/div[2]/input</value>
      <webElementGuid>8f2e9cda-569e-4977-a55c-e74815e9d4bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>0d5855e6-4264-41a0-94cd-7fc380780d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'registerPassword' and @placeholder = 'Password']</value>
      <webElementGuid>68e32d9f-283f-4a08-ada4-34b9d7682514</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
