<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tree</name>
   <tag></tag>
   <elementGuidId>50ef3af6-5ba9-4feb-8640-4bece5b4152e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dropdown-basic</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='dropdown-basic']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Tree&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>74d6ccbe-30a9-43b8-a39c-6723aae86a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8212abf4-f435-4fac-b831-654dfcf05ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdown-basic</value>
      <webElementGuid>0b2912ea-a3cd-4e39-94ec-1208e060642e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>937e983f-6239-4670-97fe-07b32c6f3cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle btn btn-secondary</value>
      <webElementGuid>818acf05-4178-424b-893a-f95aa0ece725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tree</value>
      <webElementGuid>8c065c51-4a9d-4f83-ab5f-45e7e111f092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdown-basic&quot;)</value>
      <webElementGuid>26631e92-b3f8-4797-91f9-6269e1ae34a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='dropdown-basic']</value>
      <webElementGuid>b2feade9-f1ab-4cce-8cde-983aeb27e220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/button</value>
      <webElementGuid>628d6683-bd90-4902-a217-a838c1ee5d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lengthen your body. Clasp your hands together in Anjali Mudra (also called the “prayer position”)'])[1]/preceding::button[1]</value>
      <webElementGuid>89a527a6-82be-4944-9e59-a3d2e4cc03cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Pose'])[1]/preceding::button[1]</value>
      <webElementGuid>4fbfefc7-1699-4192-8239-69152e8c29f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tree']/parent::*</value>
      <webElementGuid>786550c0-4a55-4c26-a796-b2eb8d1a4537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2970ec3f-59a1-401b-bf65-0b80f9d89a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'dropdown-basic' and (text() = 'Tree' or . = 'Tree')]</value>
      <webElementGuid>17b4b9a5-1ad3-41f2-ae3b-28e5307150fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
